#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIRECTORY="$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd
)"

CLIENT_ROOT="$(
  cd "$SCRIPT_DIRECTORY/.."
  pwd
)"

REPOSITORY_ROOT="$(
  cd "$CLIENT_ROOT/.."
  pwd
)"

CONFIG_FILE="$CLIENT_ROOT/config/client.env"

DEFAULT_BUILD_RECORD="$CLIENT_ROOT/responses/latest-build.json"
DEFAULT_DESCRIPTOR="$REPOSITORY_ROOT/controller/config/function_descriptor.json"
DEFAULT_INTENT="$REPOSITORY_ROOT/controller/config/intent.json"

BUILD_RECORD="$DEFAULT_BUILD_RECORD"
DESCRIPTOR_SOURCE="$DEFAULT_DESCRIPTOR"
INTENT_SOURCE="$DEFAULT_INTENT"
REQUEST_ID=""
INTENT_TARGET=""

usage() {
  cat <<USAGE
Usage:
  $0 [options]

Options:
  --build-record FILE   Build record generated by build_push_function.sh
                        Default: $DEFAULT_BUILD_RECORD

  --descriptor FILE     Function descriptor template
                        Default: $DEFAULT_DESCRIPTOR

  --intent FILE         Intent template
                        Default: $DEFAULT_INTENT

  --intent-target MS    Override the latency target in milliseconds

  --request-id ID       Explicit request identifier
                        Default: generated UTC identifier

  --help                Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build-record)
      BUILD_RECORD="$2"
      shift 2
      ;;
    --descriptor)
      DESCRIPTOR_SOURCE="$2"
      shift 2
      ;;
    --intent)
      INTENT_SOURCE="$2"
      shift 2
      ;;
    --intent-target)
      INTENT_TARGET="$2"
      shift 2
      ;;
    --request-id)
      REQUEST_ID="$2"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_command() {
  local command_name="$1"

  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "ERROR: Required command is not installed: $command_name" >&2
    exit 1
  fi
}

require_command python3
require_command curl

for required_file in \
  "$CONFIG_FILE" \
  "$BUILD_RECORD" \
  "$DESCRIPTOR_SOURCE" \
  "$INTENT_SOURCE"; do

  if [[ ! -f "$required_file" ]]; then
    echo "ERROR: Required file does not exist: $required_file" >&2
    exit 1
  fi
done

# shellcheck disable=SC1090
source "$CONFIG_FILE"

if [[ -z "$REQUEST_ID" ]]; then
  REQUEST_ID="request-$(date -u +%Y%m%dT%H%M%SZ)-$$"
fi

if [[ ! "$REQUEST_ID" =~ ^[A-Za-z0-9_.-]+$ ]]; then
  echo "ERROR: Invalid request ID: $REQUEST_ID" >&2
  exit 1
fi

if [[ -n "$INTENT_TARGET" ]]; then
  if ! [[ "$INTENT_TARGET" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
    echo "ERROR: Intent target must be numeric: $INTENT_TARGET" >&2
    exit 1
  fi
fi

SUBMISSION_DIRECTORY="$CLIENT_ROOT/submissions/$REQUEST_ID"

if [[ -e "$SUBMISSION_DIRECTORY" ]]; then
  echo "ERROR: Submission directory already exists:" >&2
  echo "  $SUBMISSION_DIRECTORY" >&2
  exit 1
fi

FUNCTION_NAME="$(
  python3 - "$BUILD_RECORD" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as file:
    build = json.load(file)

value = build.get("function")

if not value:
    raise SystemExit("Build record has no function name")

print(value)
PY
)"

IMAGE_TAG="$(
  python3 - "$BUILD_RECORD" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as file:
    build = json.load(file)

value = build.get("image_tag")

if not value:
    raise SystemExit("Build record has no image tag")

print(value)
PY
)"

RUNTIME_IMAGE="$(
  python3 - "$BUILD_RECORD" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as file:
    build = json.load(file)

value = build.get("runtime_image")

if not value:
    raise SystemExit("Build record has no runtime image")

print(value)
PY
)"

PUSHED_TO_VM1="$(
  python3 - "$BUILD_RECORD" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as file:
    build = json.load(file)

print("true" if build.get("pushed_to_vm1") is True else "false")
PY
)"

PUSHED_TO_VM2="$(
  python3 - "$BUILD_RECORD" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as file:
    build = json.load(file)

print("true" if build.get("pushed_to_vm2") is True else "false")
PY
)"

if [[ "$PUSHED_TO_VM1" != "true" || "$PUSHED_TO_VM2" != "true" ]]; then
  echo "ERROR: Build record does not confirm both registry pushes." >&2
  exit 1
fi

EXPECTED_RUNTIME_IMAGE="${RUNTIME_REGISTRY}/${FUNCTION_NAME}:${IMAGE_TAG}"

if [[ "$RUNTIME_IMAGE" != "$EXPECTED_RUNTIME_IMAGE" ]]; then
  echo "ERROR: Runtime image is inconsistent." >&2
  echo "Expected: $EXPECTED_RUNTIME_IMAGE" >&2
  echo "Actual:   $RUNTIME_IMAGE" >&2
  exit 1
fi

echo "===== Validating image tag in both registries ====="

VM1_TAGS="$(
  curl -fsS \
    "http://127.0.0.1:5000/v2/elif/${FUNCTION_NAME}/tags/list"
)"

VM2_TAGS="$(
  curl -fsS \
    "http://127.0.0.1:5001/v2/elif/${FUNCTION_NAME}/tags/list"
)"

python3 - \
  "$FUNCTION_NAME" \
  "$IMAGE_TAG" \
  "$VM1_TAGS" \
  "$VM2_TAGS" <<'PY'
import json
import sys

function_name = sys.argv[1]
required_tag = sys.argv[2]

registries = {
    "VM1": json.loads(sys.argv[3]),
    "VM2": json.loads(sys.argv[4]),
}

for name, response in registries.items():
    tags = response.get("tags") or []

    if required_tag not in tags:
        raise SystemExit(
            f"{name} registry does not contain "
            f"{function_name}:{required_tag}"
        )

    print(
        f"{name}: {function_name}:{required_tag} is available"
    )
PY

mkdir -p "$SUBMISSION_DIRECTORY"

DESCRIPTOR_OUTPUT="$SUBMISSION_DIRECTORY/function_descriptor.json"
INTENT_OUTPUT="$SUBMISSION_DIRECTORY/intent.json"
BUILD_OUTPUT="$SUBMISSION_DIRECTORY/build.json"
SUBMISSION_OUTPUT="$SUBMISSION_DIRECTORY/submission.json"

cp "$BUILD_RECORD" "$BUILD_OUTPUT"

python3 - \
  "$DESCRIPTOR_SOURCE" \
  "$DESCRIPTOR_OUTPUT" \
  "$FUNCTION_NAME" \
  "$RUNTIME_IMAGE" <<'PY'
import json
from pathlib import Path
import sys

source_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
function_name = sys.argv[3]
runtime_image = sys.argv[4]

with source_path.open(encoding="utf-8") as file:
    descriptor = json.load(file)

if not isinstance(descriptor, dict):
    raise SystemExit(
        "Function descriptor must contain a JSON object"
    )

descriptor["name"] = function_name
descriptor["image"] = runtime_image

# Preserve the existing schema, but update identity fields when present.
for key in ("function", "service"):
    if key in descriptor and isinstance(descriptor[key], str):
        descriptor[key] = function_name

output_path.write_text(
    json.dumps(descriptor, indent=2) + "\n",
    encoding="utf-8",
)
PY

python3 - \
  "$INTENT_SOURCE" \
  "$INTENT_OUTPUT" \
  "$FUNCTION_NAME" \
  "$INTENT_TARGET" <<'PY'
import json
from pathlib import Path
import sys

source_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
function_name = sys.argv[3]
target_override = sys.argv[4]

with source_path.open(encoding="utf-8") as file:
    intent = json.load(file)

if not isinstance(intent, dict):
    raise SystemExit(
        "Intent must contain a JSON object"
    )

intent["function"] = function_name

if target_override:
    objective = intent.get("objective")

    if not isinstance(objective, dict):
        raise SystemExit(
            "Intent has no objective object"
        )

    objective["value"] = float(target_override)

output_path.write_text(
    json.dumps(intent, indent=2) + "\n",
    encoding="utf-8",
)
PY

CREATED_AT="$(
  date -u +%Y-%m-%dT%H:%M:%SZ
)"

CLIENT_HOSTNAME="$(
  hostname
)"

python3 - \
  "$SUBMISSION_OUTPUT" \
  "$REQUEST_ID" \
  "$CREATED_AT" \
  "$CLIENT_HOSTNAME" \
  "$FUNCTION_NAME" \
  "$IMAGE_TAG" \
  "$RUNTIME_IMAGE" \
  "$DESCRIPTOR_OUTPUT" \
  "$INTENT_OUTPUT" \
  "$BUILD_OUTPUT" <<'PY'
import hashlib
import json
from pathlib import Path
import sys

(
    submission_path,
    request_id,
    created_at,
    client_hostname,
    function_name,
    image_tag,
    runtime_image,
    descriptor_path,
    intent_path,
    build_path,
) = sys.argv[1:]

descriptor_file = Path(descriptor_path)
intent_file = Path(intent_path)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(65536), b""):
            digest.update(chunk)

    return digest.hexdigest()


submission = {
    "schema_version": 1,
    "request_id": request_id,
    "created_at": created_at,
    "status": "created",
    "submitted_from": {
        "type": "macbook-client",
        "hostname": client_hostname,
    },
    "function": {
        "name": function_name,
        "image_tag": image_tag,
        "runtime_image": runtime_image,
    },
    "requested_workflow": {
        "profile_if_needed": True,
        "collect_monitoring": True,
        "select_single_cluster": True,
        "deploy_only_to_selected_cluster": True,
        "external_client_invocation": True,
        "collect_results": True,
    },
    "files": {
        "function_descriptor": "function_descriptor.json",
        "intent": "intent.json",
        "build": "build.json",
    },
    "integrity": {
        "function_descriptor_sha256": sha256(descriptor_file),
        "intent_sha256": sha256(intent_file),
    },
}

Path(submission_path).write_text(
    json.dumps(submission, indent=2) + "\n",
    encoding="utf-8",
)
PY

echo
echo "===== Validating generated JSON ====="

python3 - \
  "$DESCRIPTOR_OUTPUT" \
  "$INTENT_OUTPUT" \
  "$BUILD_OUTPUT" \
  "$SUBMISSION_OUTPUT" <<'PY'
import json
import sys

for path in sys.argv[1:]:
    with open(path, encoding="utf-8") as file:
        value = json.load(file)

    if not isinstance(value, dict):
        raise SystemExit(
            f"{path} does not contain a JSON object"
        )

    print(f"{path}: valid")
PY

echo
echo "===== Submission created ====="
echo "Request ID:           $REQUEST_ID"
echo "Function:             $FUNCTION_NAME"
echo "Image tag:            $IMAGE_TAG"
echo "Runtime image:        $RUNTIME_IMAGE"
echo "Submission directory: $SUBMISSION_DIRECTORY"
echo
echo "No deployment or placement decision was performed."
echo "SUBMISSION_DIRECTORY=$SUBMISSION_DIRECTORY"
